### PR TITLE
fix: type button and refactor SectionWrapper

### LINKED ISSUE #517: `SectionWrapper` from `SidebarList` returns `chakra.button` which incorrectly has type='submit' by default. This triggers any form if nested within a FormProvider
In `SectionWrapper` we return the default HTML button element which has `type=submit`

This results in an unintended side-effect if `Sidebar` was rendered within a `FormProvider` as clicking any of the buttons would incorrectly trigger a submit action

## To reproduce
- Nest `Sidebar` within an instantiated `FormProvider`
- Have an item be a button. In my case, i stated `label` to have `SectionWrapper` element render as a button
- Click on button, see that form submit event triggers

## Recommended fix
- Forward a default prop for button for `type=button`
    - I tried to do this but could not find a clean way to forward props over without having to create 2 wrappers.

### PR DESCRIPTION
**Pull request by austinwoon**
Closes #517

## Solution
- Refactor `SectionWrapper` to not return chakra factory, but be a conditional wrapper that forwards props over to the child chakra div or button. This is so that the `type=button` prop can be passed to the button element.

### CODE REVIEW

File: react/src/Sidebar/SidebarList.tsx [hunk 1]
```diff
@@ -54,6 +55,37 @@ export interface SidebarListProps extends BaseSidebarItemProps {
...
+
+const SectionWrapper: FC<PropsWithChildren & SectionWrapperProps> = ({
+  children,
+  onlyCaretToggle,
+  ...props
+}) => {
+  if (onlyCaretToggle) return <chakra.div {...props}>{children}</chakra.div>
+
+  return (
+    <chakra.button {...props} type="button">
```
Comment (karrui) [inline react/src/Sidebar/SidebarList.tsx:69]: should we set the `type` declaration to be before `props` destructure? in case props itself has a type override

```suggestion
    <chakra.button type="button" {...props}>
```

File: react/src/Sidebar/SidebarList.tsx [hunk 2]
```diff
@@ -54,6 +55,37 @@ export interface SidebarListProps extends BaseSidebarItemProps {
...
+  )
+}
+const ToggleChevronWrapper: FC<PropsWithChildren & SectionWrapperProps> = ({
+  children,
+  onlyCaretToggle,
+  ...props
+}) => {
+  if (onlyCaretToggle)
+    return (
+      <chakra.button {...props} type="button">
```
Comment (karrui) [inline react/src/Sidebar/SidebarList.tsx:81]: ^

**Review by karrui — APPROVED** [review]
good catch. sorry it took so long to review! will merge in after the comment is addressed

**Review by karrui — APPROVED** [review]

**Comment by karrui** [comment]
Sorry forgot
