### PR TITLE
fix(searchbar): clear controlled searchbar

### LINKED ISSUE #446: bug: Searchbar clear button doesn't trigger changes in input
**Describe the bug**
When using the Searchbar for instant searching purposes, the clear button clears the search input visually, but doesn't actually trigger changes to the `searchInput` variable (iykwim)

image

### PR DESCRIPTION
**Pull request by dextertanyj**
## Problem

Support for controlled searchbars was introduced in #218. However, the clear button does not trigger the `onChange` function and only supports uncontrolled inputs.

Closes #446 

## Solution

Check if the searchbar is a controlled input by checking for the presence of `onChange`. If it is a controlled input, call `onChange` with the appropriate value.

## Tests

- [x] Includes new story for controlled searchbar input.

### CODE REVIEW

**Comment by karrui** [comment]
FYI: @seaerchin

**Comment by seaerchin** [comment]
we pass `onSearch` only cos it's uncontrolled so idt this affects us! thx for letting me know sir @karrui

File: react/src/Searchbar/Searchbar.tsx [hunk 1]
```diff
@@ -103,14 +104,19 @@ export const Searchbar = forwardRef<SearchbarProps, 'input'>(
     )
 
     const handleClearButtonClick = useCallback(() => {
+      if (onChange) {
+        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+        // @ts-ignore
+        onChange({ target: { value: '' } })
```
Comment (seaerchin) [inline react/src/Searchbar/Searchbar.tsx:110]: if this is controlled, why is it always firing with `''` ah? just curious

Comment (dextertanyj) [reply react/src/Searchbar/Searchbar.tsx:110]: Since its controlled, we need to use `onChange` to clear the external state when the clear button is pressed so we send `''`. For all other purposes, the `onChange` function is just passed to the `Input` component which will handle everything else.

Comment (karrui) [reply react/src/Searchbar/Searchbar.tsx:110]: Should we also use the `useControllableState` hook to convert all uncontrolled/controlled props passed into the component into a controlled component? Then we can handle the current value much better.

**Review by karrui — APPROVED** [review]
lgtm
