### PR TITLE
fix: badge colors

### LINKED ISSUE #614: Bug: Change badge `Main` from info to theme colour
Currently, Badge Main is using `color-utility-feedback-info`
it should be `color-interaction-main-default`

So that when we swap themes it is reflected properly

Figma frame here: https://www.figma.com/file/40SFxTL0j4xJTnU974t5v7/%5BOGP%5D-Base-Design-System?type=design&node-id=2177-8103&mode=design&t=67INCweSXwYWeRM8-11

### PR DESCRIPTION
**Pull request by dextertanyj**
Closes #614 and fixes some other colour issues with badges.

### CODE REVIEW

File: react/src/theme/components/Badge.ts [hunk 1]
```diff
@@ -39,15 +41,17 @@ const variantSubtle = defineStyle((props) => {
...
     critical: 'utility.feedback.critical-subtle',
   }
   const subtleColorTokenMap: Record<string, string> = {
-    main: 'utility.feedback.info',
+    main: 'interaction.main.default',
     sub: 'interaction.sub.default',
+    info: 'utility.feedback.info',
     success: 'utility.feedback.success',
-    warning: 'base.content.default',
+    warning: 'yellow.700',
```
Comment (karrui) [inline react/src/theme/components/Badge.ts:54]: Why this one not token 🥲

**Review by karrui — APPROVED** [review]

File: react/src/theme/components/Badge.ts (hunk 1 above)
Comment (dextertanyj) [reply react/src/theme/components/Badge.ts:57]: @khaleedah why?

Comment (prasanthkumaar) [reply react/src/theme/components/Badge.ts:57]: @dextertanyj  I believe it's because we wanted the content of the badge to be yellow colour to match the warning background better. 

But yellow is abit tricky. If we just put utility.feedback.warning, it would look really off:
image


And currently we don't have a token name that maps to yellow.700 as it was not widely used in the system. Will check in with Pearly & Khaleedah on this!
